services:
  bot:
    image: ghcr.io/pe4enko/t-cocoa:latest
    container_name: t-cocoa-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TBANK_CA_CERT_PATH: ${TBANK_CA_CERT_PATH:-certs/TINKOFFBANK-ROOTCA.pem}
    init: true
